Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
  ViduraInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-041b17ba6ec36d948
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup